Update macOS build pipeline to 1.3
See https://gitlab.com/inkscape/infra/inkscape-ci-macosdeps/macos for
a detailed list of changes.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -143,13 +143,28 @@ inkscape:macos:
   variables:
     INK_BUILD: $CI_PIPELINE_IID
     WRK_DIR: /Users/Shared/work
+    # ICM = inkscape-ci-macos
+    ICM_VERSION: 1.3
+  before_script:
+    - |
+      git clone https://gitlab.com/inkscape/infra/inkscape-ci-macos icm
+      git -C icm checkout v$ICM_VERSION
+      git -C icm submodule update --init --recursive
+    # for more robustness in case a previous job failed
+    - icm/jhb/usr/bin/archive uninstall_dmg
   script:
-    - packaging/macos/build.sh
+    - icm/jhb/usr/bin/archive install_dmg
+    - icm/build_inkscape.sh
+    - icm/jhb/usr/bin/archive uninstall_dmg
+    # Replace the command above with this one to keep the shadow file.
+    #- icm/jhb/usr/bin/archive uninstall_dmg archive
   artifacts:
     expire_in: 1 year
     paths:
       - Inkscape*.dmg
-      - toolset_overlay.tar.xz
+      # This artifact has been disabled for now (see above) until the test job
+      # is reinstated.
+      #- "*.shadow.bz2"
 
 
 .windows:
@@ -233,9 +248,22 @@ test:linux:
   stage: test
   parallel:
     matrix:
-      - RUNNER: [ "macosintel" ]
+      - RUNNER: [ "macosarm" ]
+  needs:
+    - job: inkscape:macos
+      parallel:
+        matrix:
+          - RUNNER: macosarm
   script:
-    - packaging/macos/test.sh
+    - icm/jhb/usr/bin/archive install_dmg
+    - |
+      if ! icm/310-inkscape_test.sh; then
+        tar -C $(icm/jhb/usr/bin/config get INK_BLD_DIR) -cpJf testfiles.tar.xz testfiles Testing
+        icm/jhb/usr/bin/archive uninstall_dmg
+        exit 1
+      else
+        icm/jhb/usr/bin/archive uninstall_dmg
+      fi
   artifacts:
     paths:
       - testfiles.tar.xz
